intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{lodepng}: libul{lodepng}: {hxx cxx}{**} $impl_libs $intf_libs

libs{lodepng}: def{lodepng}: include = ($cxx.target.system == 'win32-msvc')
def{lodepng}: libul{lodepng}

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{lodepng}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{lodepng}: bin.lib.version = "-$version.project_id"
else
  lib{lodepng}: bin.lib.version = "-$version.major.$version.minor"

# Install into the lodepng/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/lodepng/
  install.subdirs = true
}
