libs =
import libs += liblodepng%lib{lodepng}

exe{pngdetail}: {hxx cxx}{**} $libs testscript

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"

# lodepng_util.h is a private helper, not a public header.
#
hxx{*}: install = false

