# Upstream libFuzzer harness (C++ API). Compile-check only when the library
# is built with C++ helpers.
#
import! [metadata, rule_hint=cxx.link] libs = liblodepng%lib{lodepng}

have_cpp = $($libs: liblodepng.cpp)

./: obje{lodepng_fuzzer}: include = $have_cpp
obje{lodepng_fuzzer}: cxx{lodepng_fuzzer} $libs
